/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DropdownSelect {
        "name": string;
        "options": string;
    }
}
declare global {
    interface HTMLDropdownSelectElement extends Components.DropdownSelect, HTMLStencilElement {
    }
    var HTMLDropdownSelectElement: {
        prototype: HTMLDropdownSelectElement;
        new (): HTMLDropdownSelectElement;
    };
    interface HTMLElementTagNameMap {
        "dropdown-select": HTMLDropdownSelectElement;
    }
}
declare namespace LocalJSX {
    interface DropdownSelect {
        "name"?: string;
        "options"?: string;
    }
    interface IntrinsicElements {
        "dropdown-select": DropdownSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dropdown-select": LocalJSX.DropdownSelect & JSXBase.HTMLAttributes<HTMLDropdownSelectElement>;
        }
    }
}
